"use client";

import dynamic from "next/dynamic";
import { Component, useEffect, useRef, useState, type ReactNode, type FormEvent } from "react";
import { AnimatePresence, motion, useInView, useReducedMotion } from "motion/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

const MarketScene = dynamic(() => import("./market-scene"), { ssr: false });
function Arrow({ diagonal = false }: { diagonal?: boolean }) { return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d={diagonal ? "M6 18 18 6M6 6h12v12" : "M4 12h15m-6-6 6 6-6 6"} stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function Mark() { return <svg width="28" height="28" viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M4 27V5h24v6H11v4h14v6H11v6H4Z" fill="currentColor"/><path d="m21 27 7-7v7h-7Z" fill="currentColor"/></svg>; }
function Spark() { return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m12 2 2.7 7.3L22 12l-7.3 2.7L12 22l-2.7-7.3L2 12l7.3-2.7L12 2Z" stroke="currentColor" strokeWidth="1.5" /></svg>; }
function Eyebrow({ children, number }: { children: ReactNode; number?: string }) { return <div className="eyebrow">{number && <span className="section-number">{number}</span>}{children}</div>; }
function Reveal({ children, className = "", delay = 0 }: { children: ReactNode; className?: string; delay?: number }) {
  const reduce = useReducedMotion();
  return <motion.div className={className} initial={false} whileInView={reduce ? {} : { opacity: [0.65, 1], y: [18, 0] }} viewport={{ once: true, amount: 0.12 }} transition={{ duration: 0.65, delay, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>;
}
class SceneBoundary extends Component<{ children: ReactNode }, { failed: boolean }> {
  state = { failed: false };
  static getDerivedStateFromError() { return { failed: true }; }
  render() { return this.state.failed ? null : this.props.children; }
}
function GlobeFallback() { return <div className="globe-fallback" aria-hidden="true"><div className="fallback-sphere">{Array.from({ length: 9 }, (_, i) => <i key={i} style={{ transform: `translate(-50%, -50%) rotate(${i * 20}deg)`, width: `${25 + (i % 4) * 18}%` }} />)}</div><div className="fallback-orbit" /></div>; }
function HeroVisual() {
  const [enabled, setEnabled] = useState(false);
  const visual = useRef<HTMLDivElement>(null);
  const visible = useInView(visual, { margin: "100px" });
  useEffect(() => {
    const query = matchMedia("(min-width: 768px) and (prefers-reduced-motion: no-preference)");
    const update = () => {
      let supported = false;
      if (query.matches) {
        try { const c = document.createElement("canvas"); const gl = c.getContext("webgl2"); supported = !!gl; gl?.getExtension("WEBGL_lose_context")?.loseContext(); } catch { supported = false; }
      }
      setEnabled(query.matches && supported);
    };
    update(); query.addEventListener("change", update);
    return () => query.removeEventListener("change", update);
  }, []);
  return <div className="hero-visual" ref={visual} role="img" aria-label="Interactive market globe connecting emerging signals, companies, and opportunities. Illustrative data.">
    <div className="visual-grid"/><div className="scan-line"/><span className="coordinate coord-top">INTELLIGENCE NETWORK / 001</span>
    <GlobeFallback />
    {enabled && <div className="scene-canvas"><SceneBoundary><MarketScene active={visible} /></SceneBoundary></div>}
    <div className="orbital-label orbital-label-one"><i/> EMERGING MARKETS</div><div className="orbital-label orbital-label-two"><i/> CONNECTED SIGNALS</div>
    <div className="floating-panel signal-panel" data-depth="-22"><div className="micro-label"><span className="status-dot"/> SIGNAL DETECTED <span>↗</span></div><strong>Agentic AI</strong><div className="signal-chart"><svg viewBox="0 0 160 38" fill="none" aria-hidden="true"><path d="m1 34 15-3 10 2 14-9 13 3 14-8 12 4 17-12 13 3 13-9 10 2 16-6" stroke="#d4f58a" strokeWidth="1.6" /></svg><span>+128%<small>market momentum</small></span></div></div>
    <div className="floating-panel opportunity-panel" data-depth="30"><div className="micro-label"><Spark/> OPPORTUNITY FOUND</div><strong>The next move.<br/><span>Before the market moves.</span></strong><div className="panel-bottom"><span>HIGH POTENTIAL</span><span className="mini-bars">▂ ▄ ▆ █</span></div></div>
    <div className="globe-caption"><span className="crosshair">+</span><span>FIND THE CONNECTIONS.<br/><b>SEE THE BIGGER PICTURE.</b></span><span className="visual-index">F / 01</span></div>
  </div>;
}
const sectors = {
  "Agentic AI": { volume: "2,846", growth: "+128%", companies: "184", opportunity: "Vertical AI agents", trend: "Enterprise adoption accelerates", activity: "New funding rounds point to demand for specialized, workflow-native agents.", points: "0,95 25,92 50,96 75,79 100,83 125,69 150,77 175,56 200,63 225,43 250,49 275,25 300,32 325,11 350,17 375,2" },
  "Climate tech": { volume: "1,392", growth: "+64%", companies: "96", opportunity: "Carbon intelligence", trend: "Carbon reporting enters the workflow", activity: "Procurement and compliance teams are looking for practical carbon data infrastructure.", points: "0,98 25,90 50,93 75,81 100,79 125,85 150,64 175,69 200,53 225,57 250,36 275,40 300,29 325,33 350,13 375,9" },
  "Fintech": { volume: "3,127", growth: "+42%", companies: "237", opportunity: "Embedded treasury", trend: "Finance moves inside the product", activity: "New platform launches bring cash management closer to everyday business operations.", points: "0,89 25,81 50,86 75,70 100,76 125,62 150,68 175,60 200,41 225,50 250,31 275,36 300,28 325,36 350,18 375,10" },
};
type Sector = keyof typeof sectors;
function Intelligence() {
  const [sector, setSector] = useState<Sector>("Agentic AI"); const data = sectors[sector];
  return <section className="section intelligence-section" id="intelligence">
    <Reveal className="section-heading"><div><Eyebrow number="01">THE SIGNAL, NOT THE NOISE</Eyebrow><h2>A world in motion.<br/><span>Your edge, in real time.</span></h2></div><p>Markets don’t wait for your next research sprint.<br className="desktop-break"/> Turn a constant stream of change into a clearer<br className="desktop-break"/> picture of what matters.</p></Reveal>
    <Reveal className="terminal"><div className="terminal-top"><div className="terminal-brand"><Mark/><span>Market pulse</span><span className="terminal-divider">/</span><span className="muted">Overview</span></div><span className="demo-badge"><span className="status-dot"/> INTERACTIVE DEMO</span></div>
      <div className="terminal-body"><aside className="terminal-sidebar"><span className="micro-label">YOUR RADAR</span><div className="sector-tabs" role="group" aria-label="Choose a market">{(Object.keys(sectors) as Sector[]).map((s, i) => <button key={s} aria-pressed={sector === s} onClick={() => setSector(s)}><span>{["◈", "◎", "↗"][i]}</span>{s}<span className="tab-arrow">↗</span></button>)}</div><div className="radar-note"><span className="radar-icon">◎</span><p>One connected view.<br/>Every meaningful move.</p></div></aside>
      <div className="terminal-main" aria-live="polite"><div className="market-title"><div><span className="micro-label">MARKET OVERVIEW</span><h3>{sector} landscape</h3></div><span className="period">Last 30 days</span></div><div className="market-metrics"><div><span>Signals analyzed</span><strong>{data.volume}<small>↗ 18.6%</small></strong></div><div><span>Market momentum</span><strong>{data.growth}<small>↑ Rising</small></strong></div><div><span>Companies on radar</span><strong>{data.companies}<small>12 new</small></strong></div></div>
      <div className="chart-head"><span>Signal activity</span><span><i/> Market interest <b>30D</b></span></div><div className="market-chart"><div className="chart-labels"><span>3k</span><span>2k</span><span>1k</span></div><svg viewBox="0 0 375 120" preserveAspectRatio="none" role="img" aria-label={`${sector} market interest trending upward over 30 days`}><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#c7ed80" stopOpacity=".16"/><stop offset="100%" stopColor="#c7ed80" stopOpacity="0"/></linearGradient></defs><path d={`M${data.points.replaceAll(" ", " L")} L375,120 L0,120 Z`} fill="url(#chartFill)"/><polyline points={data.points} fill="none" stroke="#cdeb96" strokeWidth="1.6" vectorEffect="non-scaling-stroke"/></svg></div><div className="chart-dates"><span>SEP 01</span><span>SEP 08</span><span>SEP 15</span><span>SEP 22</span><span>SEP 30</span></div>
      <div className="terminal-insight"><Spark/><p><strong>{data.opportunity}</strong> is an emerging opportunity in this market.</p><a href="#opportunities" aria-label="Explore market opportunities"><Arrow/></a></div></div>
      <aside className="signal-feed"><div className="feed-title"><span className="micro-label">SIGNAL STREAM</span><span className="status-dot"/></div><div className="feed-entry"><span className="feed-type">MARKET SHIFT <small>2m ago</small></span><h4>{data.trend}</h4><p>{data.activity}</p><span className="tag">Market activity</span></div><div className="feed-entry"><span className="feed-type">COMPETITOR MOVE <small>18m ago</small></span><h4>A new player enters the landscape</h4><p>Track positioning shifts before they become your blind spots.</p><span className="tag">Competitive intelligence</span></div><a className="text-link" href="#insights">Connect the dots <Arrow/></a></aside></div><div className="terminal-footer"><span><span className="status-dot"/> ILLUSTRATIVE DATA · NO LIVE FEED CONNECTED</span><span>POWERED BY CURIOSITY. BUILT FOR CLARITY.</span></div></Reveal>
  </section>;
}
const competitors = [{ name: "Helix", field: "Workflow automation", match: 94, color: "#d8eea9", mark: "H" }, { name: "Parallel", field: "Enterprise AI agents", match: 89, color: "#c9c0f0", mark: "∥" }, { name: "Orbit", field: "Intelligent operations", match: 86, color: "#afd1d7", mark: "◎" }];
function Competitors() {
  const [query, setQuery] = useState(""); const matches = competitors.filter(c => `${c.name} ${c.field}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="section split-section" id="competitors"><Reveal className="feature-copy"><Eyebrow number="02">COMPETITOR DISCOVERY</Eyebrow><h2>Your competition<br/>is bigger than<br/><span>your shortlist.</span></h2><p>Find the players you know. Discover the ones you don’t. Understand who’s building, where they’re heading, and what makes you different.</p><a href="#competitor-search" className="text-link">Explore the landscape <Arrow diagonal/></a><div className="feature-footnote"><span>↳</span> A wider lens. A sharper strategy.</div></Reveal><Reveal className="competitor-visual" delay={0.1}><div className="visual-header"><span className="micro-label">COMPETITIVE LANDSCAPE</span><span className="tag">SAMPLE MARKET</span></div><div className="discovery-map" aria-hidden="true"><div className="discovery-orbit orbit-a"/><div className="discovery-orbit orbit-b"/><div className="discovery-orbit orbit-c"/><svg viewBox="0 0 500 200"><path d="M250 100 95 56M250 100 390 43M250 100 414 150M250 100 126 157M250 100 292 23" stroke="#66734e" strokeDasharray="3 5"/></svg><div className="map-center"><Mark/></div><span className="map-node node-a">H</span><span className="map-node node-b">∥</span><span className="map-node node-c">◎</span><span className="map-point point-a"/><span className="map-point point-b"/></div><label className="search-box" htmlFor="competitor-search"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5" stroke="currentColor"/><path d="m16 16 5 5" stroke="currentColor"/></svg><span className="sr-only">Search competitors</span><input id="competitor-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Find a company or category…" autoComplete="off"/><span aria-hidden="true">/</span></label><div className="competitor-list" aria-live="polite">{matches.length ? matches.map(c => <div className="competitor-row" key={c.name}><span className="company-icon" style={{ color: c.color }}>{c.mark}</span><div><strong>{c.name}</strong><span>{c.field}</span></div><div className="match"><strong>{c.match}%</strong><span>relevance</span></div></div>) : <div className="empty-state">No matches for “{query}”.<button onClick={() => setQuery("")}>Clear search</button></div>}</div><span className="micro-label visual-note">ILLUSTRATIVE COMPANIES · EXPLORE THE CONNECTIONS</span></Reveal></section>;
}
const opportunities = [{ name: "Vertical AI agents", score: 92, x: "76%", y: "25%", detail: "Specialized workflows. Underserved teams. A focused entry point with room to grow.", label: "High demand · Lower saturation" }, { name: "Developer tooling", score: 78, x: "57%", y: "48%", detail: "A technically fluent audience looking for faster, more reliable ways to bring agents into production.", label: "Growing demand · Moderate saturation" }, { name: "General assistants", score: 61, x: "28%", y: "68%", detail: "An established category with broad awareness. Differentiation and distribution matter more than ever.", label: "Established demand · High saturation" }];
function Opportunities() {
  const [selected, setSelected] = useState(0); const opportunity = opportunities[selected];
  return <section className="section opportunity-section" id="opportunities"><Reveal className="opportunity-map"><div className="visual-header"><span className="micro-label">OPPORTUNITY RADAR</span><span className="map-live"><span className="status-dot"/> 3 SIGNALS MAPPED</span></div><div className="plot"><span className="plot-axis y-axis">MARKET MOMENTUM →</span><span className="plot-axis x-axis">ROOM TO DIFFERENTIATE →</span><span className="quadrant">CROWDED SPACE</span><span className="quadrant quadrant-right">THE SWEET SPOT ↗</span>{Array.from({length: 16}, (_, i) => <i className="plot-dot" key={i} style={{left: `${12 + ((i * 17) % 75)}%`, top: `${20 + ((i * 23) % 65)}%`}}/>)}{opportunities.map((o, i) => <button key={o.name} className={`opportunity-dot ${selected === i ? "selected" : ""}`} style={{ left: o.x, top: o.y }} onClick={() => setSelected(i)} aria-pressed={selected === i} aria-label={`Explore ${o.name}`}><i/><span>{o.name}</span></button>)}</div><div className="opportunity-detail" aria-live="polite"><div><span className="micro-label">{opportunity.label}</span><h3>{opportunity.name}</h3></div><div className="opportunity-score"><strong>{opportunity.score}</strong><span>/ 100<br/>potential</span></div></div><p className="opportunity-description">{opportunity.detail}</p></Reveal><Reveal className="feature-copy"><Eyebrow number="03">OPPORTUNITY MAPPING</Eyebrow><h2>See the gaps.<br/><span>Find your opening.</span></h2><p>The best opportunities aren’t always the loudest. Connect market momentum with unmet needs to see where your next big bet belongs.</p><div className="evidence-line"><span className="evidence-icon">↗</span><div><strong>From scattered signals to clear potential.</strong><span>Select a signal on the map to explore.</span></div></div><span className="micro-label">ILLUSTRATIVE OPPORTUNITY SCORES</span></Reveal></section>;
}
function Insights() {
  const [sources, setSources] = useState(false);
  return <section className="section insights-section" id="insights"><Reveal className="insights-title"><Eyebrow number="04">AI-POWERED INSIGHTS</Eyebrow><h2>More than information.<br/><span>A little foresight.</span></h2><p>Connect what happened with what it could mean.<br/>Make your next decision with the full picture.</p></Reveal><Reveal className="insight-document"><div className="document-top"><span className="insight-symbol"><Spark/></span><span>THE FABULA PERSPECTIVE</span><span className="tag">SAMPLE INSIGHT</span></div><h3>The next wave of AI<br/>won’t be general-purpose.</h3><p>As horizontal AI platforms converge, the opportunity is moving toward agents that understand one industry exceptionally well.</p><div className="insight-evidence"><span>01 / THE SIGNAL</span><p>Specialist products are gaining attention across operations, legal, and financial workflows.</p></div><div className="insight-evidence"><span>02 / THE IMPLICATION</span><p>Your domain expertise could become your most defensible advantage.</p></div><button className="sources-button" aria-expanded={sources} aria-controls="insight-sources" onClick={() => setSources(!sources)}><span><span className="source-stack">↗ ≋ ◇</span> Explore the reasoning</span><span>{sources ? "−" : "+"}</span></button><AnimatePresence initial={false}>{sources && <motion.div id="insight-sources" className="sources-content" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><strong>How this sample insight was formed</strong><p>Combines the demo’s funding signals, competitor positioning, and market-interest trends. This is illustrative analysis, not verified research.</p></motion.div>}</AnimatePresence></Reveal></section>;
}
const strategySteps = [{ name: "Find your people", caption: "IDEAL CUSTOMER PROFILE", title: "A narrower audience. A stronger starting point.", body: "Start with operations leaders at growing B2B companies. Prioritize teams with repetitive workflows and a clear cost of doing nothing.", tags: ["B2B operations", "50–500 employees", "Workflow complexity"] }, { name: "Own your difference", caption: "POSITIONING & MESSAGE", title: "Make your advantage unmistakable.", body: "Lead with domain fluency and measurable time saved. Show how a focused agent fits the tools and processes your audience already uses.", tags: ["Domain expertise", "Time to value", "Workflow-native"] }, { name: "Make your move", caption: "CHANNEL & EXPERIMENT", title: "Turn conviction into a small, testable bet.", body: "Run a focused pilot with five design partners. Measure time saved, repeat usage, and willingness to pay before widening your reach.", tags: ["5 design partners", "30-day pilot", "Measurable outcomes"] }];
function Strategy() {
  const [step, setStep] = useState(0);
  return <section className="section strategy-section" id="strategy"><Reveal className="section-heading"><div><Eyebrow number="05">GO-TO-MARKET, WITH DIRECTION</Eyebrow><h2>Intelligence is good.<br/><span>A next move is better.</span></h2></div><p>Bring your market, audience, and positioning<br className="desktop-break"/> into one coherent plan. Less second-guessing.<br className="desktop-break"/> More forward motion.</p></Reveal><Reveal className="strategy-workspace"><div className="strategy-steps" role="tablist" aria-label="Go-to-market strategy">{strategySteps.map((s, i) => <button key={s.name} role="tab" id={`strategy-tab-${i}`} aria-controls="strategy-content" aria-selected={step === i} tabIndex={step === i ? 0 : -1} onClick={() => setStep(i)} onKeyDown={e => { if (["ArrowRight", "ArrowLeft", "ArrowDown", "ArrowUp", "Home", "End"].includes(e.key)) { e.preventDefault(); const next = e.key === "Home" ? 0 : e.key === "End" ? 2 : (step + (["ArrowRight", "ArrowDown"].includes(e.key) ? 1 : 2)) % 3; setStep(next); document.getElementById(`strategy-tab-${next}`)?.focus(); } }}><span>0{i + 1}</span>{s.name}<Arrow/></button>)}</div><div className="strategy-content" id="strategy-content" role="tabpanel" aria-labelledby={`strategy-tab-${step}`} tabIndex={0}><span className="micro-label">{strategySteps[step].caption}</span><h3>{strategySteps[step].title}</h3><p>{strategySteps[step].body}</p><div className="strategy-tags">{strategySteps[step].tags.map(t => <span key={t}>{t}</span>)}</div><span className="strategy-watermark" aria-hidden="true">0{step + 1}</span></div></Reveal></section>;
}
function BriefDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null); const [complete, setComplete] = useState(false); const [market, setMarket] = useState(""); const [audience, setAudience] = useState("");
  useEffect(() => { if (open) ref.current?.showModal(); else ref.current?.close(); }, [open]);
  function download(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const content = `FABULA / MARKET EXPLORATION BRIEF\n\nMarket: ${market.trim()}\nTarget audience: ${audience.trim()}\n\n01 — MAP YOUR LANDSCAPE\nList direct competitors, adjacent products, and emerging alternatives. Compare audience, positioning, and distribution.\n\n02 — FOLLOW THE SIGNALS\nReview product launches, customer conversations, hiring, and funding announcements. Record source URLs and dates.\n\n03 — FIND YOUR OPENING\nIdentify unmet needs for ${audience.trim()}. Score each against demand, competition, and your team's strengths.\n\n04 — TEST YOUR NEXT MOVE\nChoose one positioning hypothesis in ${market.trim()}. Interview five prospective customers. Define a measurable 30-day pilot.\n\nThis is a planning template, not AI-generated market research. Created locally in your browser by the Fabula demo.\n`;
    const url = URL.createObjectURL(new Blob([content], { type: "text/plain;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "fabula-market-brief.txt"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setComplete(true);
  }
  return <dialog ref={ref} className="brief-dialog" onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose(); }} aria-labelledby="brief-title"><div className="dialog-content"><button className="dialog-close" onClick={onClose} aria-label="Close market brief">×</button><span className="dialog-mark"><Mark/></span><Eyebrow>YOUR NEXT CHAPTER</Eyebrow><h2 id="brief-title">Start with<br/>a clearer picture.</h2><p>Give your market exploration a little structure. Create a personalized planning template to take with you.</p><form onSubmit={download}><label htmlFor="brief-market">Which market are you exploring?</label><input id="brief-market" value={market} onChange={e => { setMarket(e.target.value); setComplete(false); }} placeholder="e.g. AI for healthcare operations" required maxLength={120} pattern=".*\S.*"/><label htmlFor="brief-audience">Who are you building for?</label><input id="brief-audience" value={audience} onChange={e => { setAudience(e.target.value); setComplete(false); }} placeholder="e.g. Operations teams at regional clinics" required maxLength={160} pattern=".*\S.*"/><button className="button button-primary" type="submit">{complete ? "Download again" : "Create & download brief"}<Arrow/></button><p className="form-note">Created in your browser. No signup or data submission.</p><div role="status" className="download-status">{complete && "Your brief is ready. Check your downloads."}</div></form></div></dialog>;
}
export default function Fabula() {
  const [menu, setMenu] = useState(false); const [brief, setBrief] = useState(false); const root = useRef<HTMLDivElement>(null);
  useEffect(() => {
    gsap.registerPlugin(ScrollTrigger); const mm = gsap.matchMedia();
    mm.add("(min-width: 1024px) and (prefers-reduced-motion: no-preference)", () => {
      const ctx = gsap.context(() => {
        gsap.utils.toArray<HTMLElement>("[data-depth]").forEach(el => gsap.to(el, { y: Number(el.dataset.depth), ease: "none", scrollTrigger: { trigger: ".hero", start: "top top", end: "bottom top", scrub: 1 } }));
        gsap.fromTo(".strategy-watermark", { y: 20 }, { y: -20, ease: "none", scrollTrigger: { trigger: ".strategy-section", start: "top bottom", end: "bottom top", scrub: 1 } });
      }, root); return () => ctx.revert();
    }); return () => mm.revert();
  }, []);
  return <div ref={root} className="fabula-site"><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><a href="#" className="wordmark" aria-label="Fabula home"><Mark/>fabula<span>®</span></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#intelligence">Platform <span>⌄</span></a><a href="#competitors">Why Fabula</a><a href="#strategy">The approach</a></nav><div className="header-actions"><a className="header-cta" href="#intelligence">Explore Fabula <Arrow diagonal/></a><button className="menu-toggle" aria-expanded={menu} aria-controls="mobile-nav" onClick={() => setMenu(!menu)} aria-label={menu ? "Close navigation" : "Open navigation"}>{menu ? "×" : "☰"}</button></div>{menu && <nav className="mobile-nav" id="mobile-nav" aria-label="Mobile navigation" onKeyDown={e => { if(e.key === "Escape") { setMenu(false); document.querySelector<HTMLButtonElement>(".menu-toggle")?.focus(); } }}><a href="#intelligence" onClick={() => setMenu(false)}>Platform <Arrow/></a><a href="#competitors" onClick={() => setMenu(false)}>Why Fabula <Arrow/></a><a href="#strategy" onClick={() => setMenu(false)}>The approach <Arrow/></a></nav>}</header>
    <main id="main"><section className="hero"><div className="hero-copy"><Reveal><div className="hero-kicker"><span className="status-dot"/> A NEW PERSPECTIVE ON MARKET INTELLIGENCE</div><h1>See the signals.<br/>Shape <span>what’s<br className="hero-break"/> next.</span></h1><p>Your market is telling a story. Fabula connects the dots—so you can spot the opportunities, understand the competition, and make your next move with conviction.</p><div className="hero-actions"><a href="#intelligence" className="button button-primary">Explore your market <Arrow diagonal/></a><a href="#strategy" className="button button-quiet"><span className="play-icon">▷</span> See how it works</a></div><div className="hero-caption"><span className="caption-line"/> LESS GUESSWORK. MORE FORESIGHT.</div></Reveal></div><HeroVisual/><div className="hero-bottom"><span>BUILT FOR THE CURIOUS.<br/><b>DESIGNED FOR THE DECISIVE.</b></span><a href="#intelligence">SCROLL TO DISCOVER <span>↓</span></a><span className="hero-bottom-right">YOUR NEXT CHAPTER<br/><b>STARTS WITH A SIGNAL.</b></span></div></section>
    <div className="perspective-strip"><span>A CLEARER VIEW.<br/><b>AT EVERY STAGE.</b></span><div><span className="strip-icon">⌘</span> Founders</div><div><span className="strip-icon">◈</span> Strategy teams</div><div><span className="strip-icon">↗</span> Growth leaders</div><div><span className="strip-icon">◎</span> The next big thinkers</div></div>
    <Intelligence/><div className="section-divider"><span>INTELLIGENCE, WITH PERSPECTIVE.</span><span>↓</span><span>THE FABULA ADVANTAGE</span></div><Competitors/><Opportunities/><Insights/><Strategy/>
    <section className="final-section"><div className="final-orbits" aria-hidden="true"><i/><i/><i/></div><Reveal><Eyebrow>THE FUTURE DOESN’T WAIT.</Eyebrow><h2>Be early.<br/>Be informed.<br/><span>Be the next story.</span></h2><div className="final-bottom"><p>Great companies start with a different perspective.<br/>Find yours with Fabula.</p><button className="button button-primary" onClick={() => setBrief(true)}>Create your market brief <Arrow diagonal/></button></div></Reveal></section></main>
    <footer className="site-footer"><a href="#" className="wordmark" aria-label="Fabula home"><Mark/>fabula<span>®</span></a><span>Independent thinking. Connected intelligence.</span><a href="#intelligence">Explore the demo <Arrow diagonal/></a><div className="footer-bottom"><span>© {new Date().getFullYear()} Fabula</span><span>A CONCEPT FOR WHAT COMES NEXT.</span><a href="#">Back to top ↑</a></div></footer><BriefDialog open={brief} onClose={() => setBrief(false)}/></div>;
}
